//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbYazılımSınamaEntities : DbContext
    {
        public dbYazılımSınamaEntities()
            : base("name=dbYazılımSınamaEntities6")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tblProcess> tblProcess { get; set; }
        public DbSet<tblProcessType> tblProcessType { get; set; }
        public DbSet<tblProject> tblProject { get; set; }
        public DbSet<tblSecurityQuestions> tblSecurityQuestions { get; set; }
        public DbSet<tblUserLog> tblUserLog { get; set; }
        public DbSet<tblUserProcess> tblUserProcess { get; set; }
        public DbSet<tblUserProject> tblUserProject { get; set; }
        public DbSet<tblUserRoles> tblUserRoles { get; set; }
        public DbSet<tblUsers> tblUsers { get; set; }
        public DbSet<tblWorkFlow> tblWorkFlow { get; set; }
    }
}
