//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProject
    {
        public tblProject()
        {
            this.tblUserProject = new HashSet<tblUserProject>();
        }
    
        public int projectID { get; set; }
        public string projectName { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
        public Nullable<System.DateTime> finishDate { get; set; }
        public Nullable<double> budget { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<int> createID { get; set; }
        public Nullable<int> projectManagerID { get; set; }
    
        public virtual tblUsers tblUsers { get; set; }
        public virtual tblUsers tblUsers1 { get; set; }
        public virtual ICollection<tblUserProject> tblUserProject { get; set; }
    }
}
