//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserRoles
    {
        public tblUserRoles()
        {
            this.tblUserProcess = new HashSet<tblUserProcess>();
            this.tblUserProject = new HashSet<tblUserProject>();
        }
    
        public int userRolesID { get; set; }
        public string roleName { get; set; }
    
        public virtual ICollection<tblUserProcess> tblUserProcess { get; set; }
        public virtual ICollection<tblUserProject> tblUserProject { get; set; }
    }
}
