//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUsers
    {
        public tblUsers()
        {
            this.tblProcess = new HashSet<tblProcess>();
            this.tblProcess1 = new HashSet<tblProcess>();
            this.tblProject = new HashSet<tblProject>();
            this.tblProject1 = new HashSet<tblProject>();
            this.tblUserLog = new HashSet<tblUserLog>();
        }
    
        public int userID { get; set; }
        public string userName { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public string password { get; set; }
        public Nullable<int> userRoleID { get; set; }
        public Nullable<System.DateTime> userCreateDate { get; set; }
        public Nullable<int> questionID { get; set; }
        public string answer { get; set; }
    
        public virtual ICollection<tblProcess> tblProcess { get; set; }
        public virtual ICollection<tblProcess> tblProcess1 { get; set; }
        public virtual ICollection<tblProject> tblProject { get; set; }
        public virtual ICollection<tblProject> tblProject1 { get; set; }
        public virtual ICollection<tblUserLog> tblUserLog { get; set; }
    }
}
