//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserProject
    {
        public int userProjectID { get; set; }
        public Nullable<int> userRolesID { get; set; }
        public Nullable<int> projectID { get; set; }
    
        public virtual tblProject tblProject { get; set; }
        public virtual tblUserRoles tblUserRoles { get; set; }
    }
}
