//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserLog
    {
        public int userLogID { get; set; }
        public string userLogName { get; set; }
        public Nullable<int> userID { get; set; }
        public Nullable<System.DateTime> logDate { get; set; }
    
        public virtual tblUsers tblUsers { get; set; }
    }
}
