//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWorkFlow
    {
        public int workFlowID { get; set; }
        public Nullable<int> processID { get; set; }
        public string workFlowName { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
        public Nullable<System.DateTime> finishDate { get; set; }
        public Nullable<int> userID { get; set; }
        public Nullable<int> completeRate { get; set; }
    
        public virtual tblProcess tblProcess { get; set; }
    }
}
